name: Print Secret

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Print SOME_SECRET secret value
        run: echo "Secret value:" ${{ secrets.TEST }} | sed 's/./& /g'
